### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by escowles** [pulibrary/pulbot#15]
There's a bunch of stuff from the parent project in the README that's not accurate.  It should be updated with more info about our instance.

E.g., to restart pulbot, you need to do `killall -HUP node` on `libruby-dev`

**Comment by escowles** [comment]
Also, to deploy, you can't do `bundle exec cap deploy`, you just need cap installed locally

**Comment by hackmastera** [comment]
there are some notes in https://github.com/pulibrary/pul-the-hard-way/blob/master/services/deployment.md and it's probably worth removing some of those once the pulbot README is fixed up.
