### ISSUE TITLE
Authorization through URL query param no longer valid

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulbot#51]
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Email we get: https://gist.github.com/tpendragon/cacb1889e56f0ef27ee0eb1684bceb5b

**Comment by jrgriffiniii** [comment]
As of 05/05/21, I am finding that this is blocking deployments.

**Comment by jrgriffiniii** [comment]
One solution proposed by @tpendragon  is to integrate support for hubot-deploy and update octokit.
